---
name: HTML-GenToc
version: 3.00
author:
  - Kathryn Andersen
abstract: generate a table of contents for HTML documents
license: gpl
resources:
  license: http://www.opensource.org/licenses/gpl-license.php
requires:
  Data::Dumper: 0
  Getopt::ArgvFile: 1.09
  Getopt::Long: 2.34
  HTML::LinkList: 0.1501
  HTML::SimpleParse: 0.1
  Pod::Usage: 0
build_requires:
  Test::More: 0
provides:
  HTML::GenToc:
    file: lib/HTML/GenToc.pm
    version: 3.00
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
